// <auto-generated />
using DogBreedApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DogBreedApp.Migrations
{
    [DbContext(typeof(DogContext))]
    [Migration("20180723190856_BreedAndCharacteristicsSeparation")]
    partial class BreedAndCharacteristicsSeparation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DogBreedApp.Data.Entities.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("DogBreedApp.Data.Entities.BreedCharacteristic", b =>
                {
                    b.Property<int>("BreedId");

                    b.Property<int>("CharacteristicId");

                    b.Property<int>("Score");

                    b.HasKey("BreedId", "CharacteristicId");

                    b.HasIndex("CharacteristicId");

                    b.ToTable("BreedCharacteristic");
                });

            modelBuilder.Entity("DogBreedApp.Data.Entities.Characteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("DogBreedApp.Data.Entities.BreedCharacteristic", b =>
                {
                    b.HasOne("DogBreedApp.Data.Entities.Breed", "Breed")
                        .WithMany("BreedCharacteristics")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DogBreedApp.Data.Entities.Characteristic", "Characteristic")
                        .WithMany("BreedCharacteristics")
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
